Create InProgress Page which includes Conditional Rendering using Boolean variable.
starteryouInc/Starteryou-Website pull request #26
Opened 2024-12-02 16:19 UTC by DPriyankaChowdary

A new InProgress Page has been created to act as a placeholder for pages or features that are not yet ready for deployment. The integration includes a conditional rendering mechanism using a boolean variable called deployReady. 

deployReady = true: The target page or feature is rendered, making it available for users.
deployReady = false: The InProgress Page is rendered, signaling that the feature or page is not yet available.

[InProgressPage](https://github.com/starteryouInc/Starteryou-Website/blob/778cd9755a631526bd7beeaad7e7cab1520af08d/Starteryou/frontend/src/pages/InProgressPage.jsx)

2024-12-02 17:44 UTC, MdAsifSid requested changes
Move this file to the common folder, which is inside the components directory.

2024-12-02 17:44 UTC, MdAsifSid commented on Starteryou/frontend/src/pages/InProgressPage.jsx
Move this file to the common folder, which is inside the components directory.

2024-12-02 18:24 UTC, DPriyankaChowdary commented on Starteryou/frontend/src/pages/InProgressPage.jsx
I have made the changes.

2024-12-03 05:09 UTC, MdAsifSid approved these changes

2024-12-08 20:04 UTC, nikshepkulli-CTO approved these changes

2024-12-08 20:07 UTC, merged